project:
  type: website
  output-dir: docs

author: 
    name: "José Ramón Hernández Aguilar"
    email: hdezagjr@gmail.com
date: "07/06/2025"

lang: es
language:
  title-block-author-single: "Autor"

website: 
  favicon: data/walmart.ico